/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BancodeDados;

import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;

/**
 *
 * @author m72583
 */
public class TelaPrincipal extends javax.swing.JFrame {
    TelaInserir ti;
    TelaExcluir te;
    TelaConsultar tc;
    TelaMedia tm;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setSize(600, 600);
        
        ti = new TelaInserir(); 
        this.ti.setVisible(false);        
        this.getContentPane().add(ti);
       
        
        te = new TelaExcluir();
        this.te.setVisible(false);
        this.getContentPane().add(te);
       
        
        tc = new TelaConsultar();
        this.tc.setVisible(false);
        this.getContentPane().add(tc);
        
        
        tm = new TelaMedia();
        this.tm.setVisible(false);
        this.getContentPane().add(tm);
        
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inserir = new javax.swing.JToggleButton();
        excluir = new javax.swing.JToggleButton();
        consultar = new javax.swing.JToggleButton();
        media = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inserir.setText("Inserir");
        inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserirMouseClicked(evt);
            }
        });
        getContentPane().add(inserir);
        inserir.setBounds(23, 56, 81, 23);

        excluir.setText("Excluir");
        excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMouseClicked(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(23, 97, 81, 23);

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(25, 138, 79, 23);

        media.setText("Média");
        media.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediaMouseClicked(evt);
            }
        });
        getContentPane().add(media);
        media.setBounds(25, 184, 79, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserirMouseClicked
          
 
         if(ti.isVisible())
           ti.setVisible(false);
        else
          ti.setVisible(true);         
         ti.setLocation(200, -100);
    
    }//GEN-LAST:event_inserirMouseClicked

    private void excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMouseClicked
         if(te.isVisible())
           te.setVisible(false);
        else
          te.setVisible(true);         
          te.setLocation(200, -100);
    }//GEN-LAST:event_excluirMouseClicked

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        if(tc.isVisible())
           tc.setVisible(false);
        else
          tc.setVisible(true);         
          tc.setLocation(200, -100);
    }//GEN-LAST:event_consultarMouseClicked

    private void mediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediaMouseClicked
       if(tm.isVisible())
           tm.setVisible(false);
        else
          tm.setVisible(true);         
          tm.setLocation(200, -100);
    }//GEN-LAST:event_mediaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton consultar;
    private javax.swing.JToggleButton excluir;
    private javax.swing.JToggleButton inserir;
    private javax.swing.JToggleButton media;
    // End of variables declaration//GEN-END:variables
}
