/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula4grafico;
import java.util.ArrayList;
import java.util.LinkedList;
/**
 *
 * @author m80027
 */
public class InserePessoa extends javax.swing.JPanel {
   LinkedList<Pessoa> pessoas =  new LinkedList<>() ;
    /**
     * Creates new form InserePessoa
     */
    public InserePessoa() {
        initComponents();
        this.setSize(400,300);
        this.setVisible(false);
      
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNomePainelPessoa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inserirPessoaPainelPessoa = new javax.swing.JButton();
        voltarPainelPessoaToPrincipal = new javax.swing.JButton();
        listarPessoas = new javax.swing.JButton();
        campoIdadePainelPessoa = new javax.swing.JFormattedTextField();

        campoNomePainelPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomePainelPessoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade");

        inserirPessoaPainelPessoa.setText("Inserir");
        inserirPessoaPainelPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirPessoaPainelPessoaActionPerformed(evt);
            }
        });

        voltarPainelPessoaToPrincipal.setText("Voltar");
        voltarPainelPessoaToPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarPainelPessoaToPrincipalActionPerformed(evt);
            }
        });

        listarPessoas.setText("Listar Pessoas");
        listarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPessoasActionPerformed(evt);
            }
        });

        campoIdadePainelPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdadePainelPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserirPessoaPainelPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltarPainelPessoaToPrincipal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoIdadePainelPessoa))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(campoNomePainelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNomePainelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoIdadePainelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inserirPessoaPainelPessoa)
                        .addComponent(listarPessoas))
                    .addComponent(voltarPainelPessoaToPrincipal))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomePainelPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomePainelPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomePainelPessoaActionPerformed

    private void inserirPessoaPainelPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirPessoaPainelPessoaActionPerformed
        Pessoa p = new Pessoa(campoNomePainelPessoa.getText(), Integer.parseInt(campoIdadePainelPessoa.getText()));
        this.addPessoa(p);
    }//GEN-LAST:event_inserirPessoaPainelPessoaActionPerformed

    private void voltarPainelPessoaToPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarPainelPessoaToPrincipalActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_voltarPainelPessoaToPrincipalActionPerformed

    private void listarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPessoasActionPerformed
        this.mostrarPessoas();
    }//GEN-LAST:event_listarPessoasActionPerformed

    private void campoIdadePainelPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdadePainelPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdadePainelPessoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoIdadePainelPessoa;
    public javax.swing.JTextField campoNomePainelPessoa;
    public javax.swing.JButton inserirPessoaPainelPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton listarPessoas;
    public javax.swing.JButton voltarPainelPessoaToPrincipal;
    // End of variables declaration//GEN-END:variables

 public void addPessoa(Pessoa p) {       
            pessoas.add(p);
 }
    
 public void mostrarPessoas(){
     for (Pessoa pessoa : pessoas) {
         System.out.println(pessoa.getNome()+ " - " + pessoa.getDataNascimento());
     }
    
}
 }



