/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula4grafico;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author m80027
 */
public class PainelPrincipal extends javax.swing.JFrame implements ActionListener {

    InserePessoa ip;
    PainelGrafico pg;
    

    /* EventoInt ei;
    EventoDentro ed;*/
    /**
     * Creates new form PrincEventos
     */
    public PainelPrincipal() {
        initComponents();
        ip = new InserePessoa();
        pg = new PainelGrafico();
        this.setSize(600,400);
        this.setBounds(0, 0, this.getWidth(), this.getHeight());
       
        this.getContentPane().add(ip); 
        this.getContentPane().add(pg);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        cadastrarPessoa = new javax.swing.JMenuItem();
        geradorDeGrafico = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));

        menu.setLabel("Menu");

        cadastrarPessoa.setText("Inserir Pesosa");
        cadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPessoaActionPerformed(evt);
            }
        });
        menu.add(cadastrarPessoa);

        geradorDeGrafico.setText("Gerador de gráfico");
        geradorDeGrafico.setActionCommand("");
        geradorDeGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geradorDeGraficoActionPerformed(evt);
            }
        });
        menu.add(geradorDeGrafico);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPessoaActionPerformed
       if (ip.isVisible()) {
           ip.setVisible(false);
       } else {
          ip.setVisible(true);
          pg.setVisible(false);
       }
    }//GEN-LAST:event_cadastrarPessoaActionPerformed

    private void geradorDeGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geradorDeGraficoActionPerformed
      if (pg.isVisible()) {
            pg.setVisible(false);
      }else{
            pg.setVisible(true);
            ip.setVisible(false);
      }
      pg.mostrarCamposGeracaoGrafico();
    }//GEN-LAST:event_geradorDeGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarPessoa;
    public javax.swing.JMenuItem geradorDeGrafico;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables

    @Override   
    public void actionPerformed(ActionEvent e) {
      
        
       

    }
 

}
