/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import server.*;
import cliente.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author rodrigolucke
 */
public class BatalhaClienteTela extends javax.swing.JFrame implements ActionListener {
   
    //Socket socket =new Socket("192.168.1.112", 5000);
    Socket socket; 
    Player player;
    Player oponente;
   
    String caminhoImagens = "./src/images/";
    Icon defaultIcon = new ImageIcon(caminhoImagens+"charada.gif");
    Icon iconAcertou = new ImageIcon(caminhoImagens+"acertou.gif");
    Icon iconErrou = new ImageIcon(caminhoImagens+"errou.gif");
    
    
  //  Tabuleiro tabuleiroOponente;
    private DataInputStream in; // canal de entrada
    private DataOutputStream out; // canal de saida
    
    

    /**
     * Creates new form BatalgaClienteTela
     * @throws java.io.IOException
     */
    
    public BatalhaClienteTela(int inicio) {
        
        
        
    }

    public BatalhaClienteTela() throws IOException {
        int server = JOptionPane.showConfirmDialog(this, "Você deseja iniciar o server?");
          
          
          if( server ==0){
            Server servidor = new Server();
          }
        initComponents();
        
        
        String ip = JOptionPane.showInputDialog("Digide o ip do servidor"); 
        //this.socket =new Socket("192.168.1.112", 5000);
        this.socket =new Socket(ip, 5000);
        
	        
        //defaultIcon = new ImageIcon("C:/Users/rodrigolucke/Documents/NetBeansProjects/BatalhaNavalLuckeDani/src/images.gif");
        
        
        this.setarIconesDefault();
       
        this.setSize(900, 650);
        String nomeJogador = JOptionPane.showInputDialog("Digide seu nome");        
        this.player = new Player( nomeJogador, 0);
        JOptionPane.showMessageDialog(this, "Bem vindo \n"+ player.getNome());
        this.player.setVida(this.player.calcularVidaPlayer());
        this.vidaRestante.setText(Integer.toString( this.getPlayer().getVida()));
        this.desbloqueiaJogada();
        this.envio.setVisible(true);
        
        configurarRede(this);
    }

    public Socket getSocket() {
        return socket;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

  /*  public Tabuleiro getTabuleiroPlayer() {
        return tabuleiroPlayer;
    }

    public void setTabuleiroPlayer(Tabuleiro tabuleiroPlayer) {
        this.tabuleiroPlayer = tabuleiroPlayer;
    }

    public Tabuleiro getTabuleiroOponente() {
        return tabuleiroOponente;
    }

    public void setTabuleiroOponente(Tabuleiro tabuleiroOponente) {
        this.tabuleiroOponente = tabuleiroOponente;
    }*/

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        envio = new javax.swing.JPanel();
        l1 = new javax.swing.JButton();
        l2 = new javax.swing.JButton();
        l3 = new javax.swing.JButton();
        errou = new javax.swing.JButton();
        l5 = new javax.swing.JButton();
        l6 = new javax.swing.JButton();
        l7 = new javax.swing.JButton();
        l8 = new javax.swing.JButton();
        l9 = new javax.swing.JButton();
        l10 = new javax.swing.JButton();
        l11 = new javax.swing.JButton();
        l12 = new javax.swing.JButton();
        l13 = new javax.swing.JButton();
        l14 = new javax.swing.JButton();
        l15 = new javax.swing.JButton();
        l16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l4 = new javax.swing.JButton();
        acertou = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        envio1 = new javax.swing.JPanel();
        l17 = new javax.swing.JButton();
        l18 = new javax.swing.JButton();
        l19 = new javax.swing.JButton();
        errou1 = new javax.swing.JButton();
        l20 = new javax.swing.JButton();
        l21 = new javax.swing.JButton();
        l22 = new javax.swing.JButton();
        l23 = new javax.swing.JButton();
        l24 = new javax.swing.JButton();
        l25 = new javax.swing.JButton();
        l26 = new javax.swing.JButton();
        l27 = new javax.swing.JButton();
        l28 = new javax.swing.JButton();
        l29 = new javax.swing.JButton();
        l30 = new javax.swing.JButton();
        l31 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l32 = new javax.swing.JButton();
        acertou1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        suaVez = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vidaRestante = new javax.swing.JButton();
        envio2 = new javax.swing.JPanel();
        l33 = new javax.swing.JButton();
        l34 = new javax.swing.JButton();
        l35 = new javax.swing.JButton();
        l36 = new javax.swing.JButton();
        l37 = new javax.swing.JButton();
        l38 = new javax.swing.JButton();
        l39 = new javax.swing.JButton();
        l40 = new javax.swing.JButton();
        l41 = new javax.swing.JButton();
        l42 = new javax.swing.JButton();
        l43 = new javax.swing.JButton();
        l44 = new javax.swing.JButton();
        l45 = new javax.swing.JButton();
        l46 = new javax.swing.JButton();
        l47 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        l48 = new javax.swing.JButton();
        envio3 = new javax.swing.JPanel();
        l49 = new javax.swing.JButton();
        l50 = new javax.swing.JButton();
        l51 = new javax.swing.JButton();
        errou3 = new javax.swing.JButton();
        l52 = new javax.swing.JButton();
        l53 = new javax.swing.JButton();
        l54 = new javax.swing.JButton();
        l55 = new javax.swing.JButton();
        l56 = new javax.swing.JButton();
        l57 = new javax.swing.JButton();
        l58 = new javax.swing.JButton();
        l59 = new javax.swing.JButton();
        l60 = new javax.swing.JButton();
        l61 = new javax.swing.JButton();
        l62 = new javax.swing.JButton();
        l63 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        l64 = new javax.swing.JButton();
        acertou3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        envio.setLayout(null);

        l1.setText("0");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        envio.add(l1);
        l1.setBounds(30, 60, 70, 50);

        l2.setText("1");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        envio.add(l2);
        l2.setBounds(110, 60, 70, 50);

        l3.setText("2");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        envio.add(l3);
        l3.setBounds(190, 60, 70, 50);

        errou.setText("3");
        errou.setActionCommand("2");
        errou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                errouMouseClicked(evt);
            }
        });
        envio.add(errou);
        errou.setBounds(140, 350, 70, 50);

        l5.setText("4");
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        envio.add(l5);
        l5.setBounds(30, 120, 70, 50);

        l6.setText("5");
        l6.setActionCommand("2");
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        envio.add(l6);
        l6.setBounds(110, 120, 70, 50);

        l7.setText("6");
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        envio.add(l7);
        l7.setBounds(190, 120, 70, 50);

        l8.setText("7");
        l8.setActionCommand("2");
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        envio.add(l8);
        l8.setBounds(270, 120, 70, 50);

        l9.setText("8");
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        envio.add(l9);
        l9.setBounds(30, 180, 70, 50);

        l10.setText("9");
        l10.setActionCommand("2");
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        envio.add(l10);
        l10.setBounds(110, 180, 70, 50);

        l11.setText("10");
        l11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l11MouseClicked(evt);
            }
        });
        envio.add(l11);
        l11.setBounds(190, 180, 70, 50);

        l12.setText("11");
        l12.setActionCommand("2");
        l12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l12MouseClicked(evt);
            }
        });
        envio.add(l12);
        l12.setBounds(270, 180, 70, 50);

        l13.setText("12");
        l13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l13MouseClicked(evt);
            }
        });
        envio.add(l13);
        l13.setBounds(30, 240, 70, 50);

        l14.setText("13");
        l14.setActionCommand("2");
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l14MouseClicked(evt);
            }
        });
        envio.add(l14);
        l14.setBounds(110, 240, 70, 50);

        l15.setText("14");
        l15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l15MouseClicked(evt);
            }
        });
        envio.add(l15);
        l15.setBounds(190, 240, 70, 50);

        l16.setText("15");
        l16.setActionCommand("2");
        l16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l16MouseClicked(evt);
            }
        });
        envio.add(l16);
        l16.setBounds(270, 240, 70, 50);

        jLabel1.setText("Tabuleiro Oponente");
        envio.add(jLabel1);
        jLabel1.setBounds(120, 0, 95, 14);

        jLabel2.setText("Legendas:");
        envio.add(jLabel2);
        jLabel2.setBounds(20, 340, 50, 14);

        l4.setText("3");
        l4.setActionCommand("2");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        envio.add(l4);
        l4.setBounds(270, 60, 70, 50);

        acertou.setText("3");
        acertou.setActionCommand("2");
        acertou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acertouMouseClicked(evt);
            }
        });
        envio.add(acertou);
        acertou.setBounds(140, 300, 70, 50);

        jLabel4.setText("Acertou:");
        envio.add(jLabel4);
        jLabel4.setBounds(90, 320, 42, 14);

        jLabel5.setText("Errou:");
        envio.add(jLabel5);
        jLabel5.setBounds(100, 360, 30, 30);

        envio1.setLayout(null);

        l17.setText("0");
        l17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l17MouseClicked(evt);
            }
        });
        envio1.add(l17);
        l17.setBounds(40, 30, 70, 50);

        l18.setText("1");
        l18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l18MouseClicked(evt);
            }
        });
        envio1.add(l18);
        l18.setBounds(120, 30, 70, 50);

        l19.setText("2");
        l19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l19MouseClicked(evt);
            }
        });
        envio1.add(l19);
        l19.setBounds(200, 30, 70, 50);

        errou1.setText("3");
        errou1.setActionCommand("2");
        errou1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                errou1MouseClicked(evt);
            }
        });
        envio1.add(errou1);
        errou1.setBounds(130, 350, 70, 50);

        l20.setText("4");
        l20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l20MouseClicked(evt);
            }
        });
        envio1.add(l20);
        l20.setBounds(40, 90, 70, 50);

        l21.setText("5");
        l21.setActionCommand("2");
        l21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l21MouseClicked(evt);
            }
        });
        envio1.add(l21);
        l21.setBounds(120, 90, 70, 50);

        l22.setText("6");
        l22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l22MouseClicked(evt);
            }
        });
        envio1.add(l22);
        l22.setBounds(200, 90, 70, 50);

        l23.setText("7");
        l23.setActionCommand("2");
        l23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l23MouseClicked(evt);
            }
        });
        envio1.add(l23);
        l23.setBounds(280, 90, 70, 50);

        l24.setText("8");
        l24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l24MouseClicked(evt);
            }
        });
        envio1.add(l24);
        l24.setBounds(40, 150, 70, 50);

        l25.setText("9");
        l25.setActionCommand("2");
        l25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l25MouseClicked(evt);
            }
        });
        envio1.add(l25);
        l25.setBounds(120, 150, 70, 50);

        l26.setText("10");
        l26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l26MouseClicked(evt);
            }
        });
        envio1.add(l26);
        l26.setBounds(200, 150, 70, 50);

        l27.setText("11");
        l27.setActionCommand("2");
        l27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l27MouseClicked(evt);
            }
        });
        envio1.add(l27);
        l27.setBounds(280, 150, 70, 50);

        l28.setText("12");
        l28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l28MouseClicked(evt);
            }
        });
        envio1.add(l28);
        l28.setBounds(40, 210, 70, 50);

        l29.setText("13");
        l29.setActionCommand("2");
        l29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l29MouseClicked(evt);
            }
        });
        envio1.add(l29);
        l29.setBounds(120, 210, 70, 50);

        l30.setText("14");
        l30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l30MouseClicked(evt);
            }
        });
        envio1.add(l30);
        l30.setBounds(200, 210, 70, 50);

        l31.setText("15");
        l31.setActionCommand("2");
        l31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l31MouseClicked(evt);
            }
        });
        envio1.add(l31);
        l31.setBounds(280, 210, 70, 50);

        jLabel6.setText("Tabuleiro Oponente");
        envio1.add(jLabel6);
        jLabel6.setBounds(130, 10, 95, 14);

        jLabel7.setText("Legendas:");
        envio1.add(jLabel7);
        jLabel7.setBounds(70, 260, 50, 14);

        l32.setText("3");
        l32.setActionCommand("2");
        l32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l32MouseClicked(evt);
            }
        });
        envio1.add(l32);
        l32.setBounds(280, 30, 70, 50);

        acertou1.setText("3");
        acertou1.setActionCommand("2");
        acertou1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acertou1MouseClicked(evt);
            }
        });
        envio1.add(acertou1);
        acertou1.setBounds(130, 290, 70, 50);

        jLabel8.setText("Acertou:");
        envio1.add(jLabel8);
        jLabel8.setBounds(60, 300, 42, 14);

        jLabel9.setText("Errou:");
        envio1.add(jLabel9);
        jLabel9.setBounds(60, 360, 30, 30);

        envio.add(envio1);
        envio1.setBounds(0, 0, 0, 0);

        suaVez.setText("Sua vez de jogar, efetue Sua Jogada aqui!");
        envio.add(suaVez);
        suaVez.setBounds(30, 23, 310, 30);

        jLabel3.setText("Vida Restante:");
        envio.add(jLabel3);
        jLabel3.setBounds(270, 310, 71, 14);
        envio.add(vidaRestante);
        vidaRestante.setBounds(280, 330, 58, 33);

        envio2.setLayout(null);

        l33.setText("0");
        l33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l33MouseClicked(evt);
            }
        });
        envio2.add(l33);
        l33.setBounds(20, 70, 70, 50);

        l34.setText("1");
        l34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l34MouseClicked(evt);
            }
        });
        envio2.add(l34);
        l34.setBounds(100, 70, 70, 50);

        l35.setText("2");
        l35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l35MouseClicked(evt);
            }
        });
        envio2.add(l35);
        l35.setBounds(180, 70, 70, 50);

        l36.setText("4");
        l36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l36MouseClicked(evt);
            }
        });
        envio2.add(l36);
        l36.setBounds(20, 130, 70, 50);

        l37.setText("5");
        l37.setActionCommand("2");
        l37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l37MouseClicked(evt);
            }
        });
        envio2.add(l37);
        l37.setBounds(100, 130, 70, 50);

        l38.setText("6");
        l38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l38MouseClicked(evt);
            }
        });
        envio2.add(l38);
        l38.setBounds(180, 130, 70, 50);

        l39.setText("7");
        l39.setActionCommand("2");
        l39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l39MouseClicked(evt);
            }
        });
        envio2.add(l39);
        l39.setBounds(260, 130, 70, 50);

        l40.setText("8");
        l40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l40MouseClicked(evt);
            }
        });
        envio2.add(l40);
        l40.setBounds(20, 190, 70, 50);

        l41.setText("9");
        l41.setActionCommand("2");
        l41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l41MouseClicked(evt);
            }
        });
        envio2.add(l41);
        l41.setBounds(100, 190, 70, 50);

        l42.setText("10");
        l42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l42MouseClicked(evt);
            }
        });
        envio2.add(l42);
        l42.setBounds(180, 190, 70, 50);

        l43.setText("11");
        l43.setActionCommand("2");
        l43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l43MouseClicked(evt);
            }
        });
        envio2.add(l43);
        l43.setBounds(260, 190, 70, 50);

        l44.setText("12");
        l44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l44MouseClicked(evt);
            }
        });
        envio2.add(l44);
        l44.setBounds(20, 250, 70, 50);

        l45.setText("13");
        l45.setActionCommand("2");
        l45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l45MouseClicked(evt);
            }
        });
        envio2.add(l45);
        l45.setBounds(100, 250, 70, 50);

        l46.setText("14");
        l46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l46MouseClicked(evt);
            }
        });
        envio2.add(l46);
        l46.setBounds(180, 250, 70, 50);

        l47.setText("15");
        l47.setActionCommand("2");
        l47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l47MouseClicked(evt);
            }
        });
        envio2.add(l47);
        l47.setBounds(260, 250, 70, 50);

        jLabel10.setText("Seu tabulleiro:");
        envio2.add(jLabel10);
        jLabel10.setBounds(130, 10, 69, 14);

        l48.setText("3");
        l48.setActionCommand("2");
        l48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l48MouseClicked(evt);
            }
        });
        envio2.add(l48);
        l48.setBounds(260, 70, 70, 50);

        envio3.setLayout(null);

        l49.setText("0");
        l49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l49MouseClicked(evt);
            }
        });
        envio3.add(l49);
        l49.setBounds(40, 30, 70, 50);

        l50.setText("1");
        l50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l50MouseClicked(evt);
            }
        });
        envio3.add(l50);
        l50.setBounds(120, 30, 70, 50);

        l51.setText("2");
        l51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l51MouseClicked(evt);
            }
        });
        envio3.add(l51);
        l51.setBounds(200, 30, 70, 50);

        errou3.setText("3");
        errou3.setActionCommand("2");
        errou3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                errou3MouseClicked(evt);
            }
        });
        envio3.add(errou3);
        errou3.setBounds(130, 350, 70, 50);

        l52.setText("4");
        l52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l52MouseClicked(evt);
            }
        });
        envio3.add(l52);
        l52.setBounds(40, 90, 70, 50);

        l53.setText("5");
        l53.setActionCommand("2");
        l53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l53MouseClicked(evt);
            }
        });
        envio3.add(l53);
        l53.setBounds(120, 90, 70, 50);

        l54.setText("6");
        l54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l54MouseClicked(evt);
            }
        });
        envio3.add(l54);
        l54.setBounds(200, 90, 70, 50);

        l55.setText("7");
        l55.setActionCommand("2");
        l55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l55MouseClicked(evt);
            }
        });
        envio3.add(l55);
        l55.setBounds(280, 90, 70, 50);

        l56.setText("8");
        l56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l56MouseClicked(evt);
            }
        });
        envio3.add(l56);
        l56.setBounds(40, 150, 70, 50);

        l57.setText("9");
        l57.setActionCommand("2");
        l57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l57MouseClicked(evt);
            }
        });
        envio3.add(l57);
        l57.setBounds(120, 150, 70, 50);

        l58.setText("10");
        l58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l58MouseClicked(evt);
            }
        });
        envio3.add(l58);
        l58.setBounds(200, 150, 70, 50);

        l59.setText("11");
        l59.setActionCommand("2");
        l59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l59MouseClicked(evt);
            }
        });
        envio3.add(l59);
        l59.setBounds(280, 150, 70, 50);

        l60.setText("12");
        l60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l60MouseClicked(evt);
            }
        });
        envio3.add(l60);
        l60.setBounds(40, 210, 70, 50);

        l61.setText("13");
        l61.setActionCommand("2");
        l61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l61MouseClicked(evt);
            }
        });
        envio3.add(l61);
        l61.setBounds(120, 210, 70, 50);

        l62.setText("14");
        l62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l62MouseClicked(evt);
            }
        });
        envio3.add(l62);
        l62.setBounds(200, 210, 70, 50);

        l63.setText("15");
        l63.setActionCommand("2");
        l63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l63MouseClicked(evt);
            }
        });
        envio3.add(l63);
        l63.setBounds(280, 210, 70, 50);

        jLabel14.setText("Tabuleiro Oponente");
        envio3.add(jLabel14);
        jLabel14.setBounds(130, 10, 95, 14);

        jLabel15.setText("Legendas:");
        envio3.add(jLabel15);
        jLabel15.setBounds(70, 260, 50, 14);

        l64.setText("3");
        l64.setActionCommand("2");
        l64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l64MouseClicked(evt);
            }
        });
        envio3.add(l64);
        l64.setBounds(280, 30, 70, 50);

        acertou3.setText("3");
        acertou3.setActionCommand("2");
        acertou3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acertou3MouseClicked(evt);
            }
        });
        envio3.add(acertou3);
        acertou3.setBounds(130, 290, 70, 50);

        jLabel16.setText("Acertou:");
        envio3.add(jLabel16);
        jLabel16.setBounds(60, 300, 42, 14);

        jLabel17.setText("Errou:");
        envio3.add(jLabel17);
        jLabel17.setBounds(60, 360, 30, 30);

        envio2.add(envio3);
        envio3.setBounds(0, 0, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(envio, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(envio2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(envio, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(envio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
       
         try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l1.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l2.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
         try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l3.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l3MouseClicked

    private void errouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errouMouseClicked
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(errou.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_errouMouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
  
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l5.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
       
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l6.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l7.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
          try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l8.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
        
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l9.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_l9MouseClicked

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
        
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l10.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l10MouseClicked

    private void l11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l11MouseClicked
          
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l11.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l11MouseClicked

    private void l12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l12MouseClicked
        
         
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l12.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l12MouseClicked

    private void l13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l13MouseClicked
          
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l13.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l13MouseClicked

    private void l14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseClicked
          
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l14.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l14MouseClicked

    private void l15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l15MouseClicked
       
        
        try {
            in = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
       // escritor.println(l16.getText());
        try {
            out.writeUTF(l15.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l15MouseClicked

    private void l16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l16MouseClicked
       
        
        try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        try {
            out.writeUTF(l16.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_l16MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
         try {   
            out = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        try {
            out.writeUTF(l4.getText());
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_l4MouseClicked

    private void acertouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acertouMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acertouMouseClicked

    private void l17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l17MouseClicked

    private void l18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l18MouseClicked

    private void l19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l19MouseClicked

    private void errou1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errou1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_errou1MouseClicked

    private void l20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l20MouseClicked

    private void l21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l21MouseClicked

    private void l22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l22MouseClicked

    private void l23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l23MouseClicked

    private void l24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l24MouseClicked

    private void l25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l25MouseClicked

    private void l26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l26MouseClicked

    private void l27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l27MouseClicked

    private void l28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l28MouseClicked

    private void l29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l29MouseClicked

    private void l30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l30MouseClicked

    private void l31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l31MouseClicked

    private void l32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l32MouseClicked

    private void acertou1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acertou1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acertou1MouseClicked

    private void l33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l33MouseClicked

    private void l34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l34MouseClicked

    private void l35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l35MouseClicked

    private void l36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l36MouseClicked

    private void l37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l37MouseClicked

    private void l38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l38MouseClicked

    private void l39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l39MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l39MouseClicked

    private void l40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l40MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l40MouseClicked

    private void l41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l41MouseClicked

    private void l42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l42MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l42MouseClicked

    private void l43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l43MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l43MouseClicked

    private void l44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l44MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l44MouseClicked

    private void l45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l45MouseClicked

    private void l46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l46MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l46MouseClicked

    private void l47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l47MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l47MouseClicked

    private void l48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l48MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l48MouseClicked

    private void l49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l49MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l49MouseClicked

    private void l50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l50MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l50MouseClicked

    private void l51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l51MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l51MouseClicked

    private void errou3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errou3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_errou3MouseClicked

    private void l52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l52MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l52MouseClicked

    private void l53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l53MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l53MouseClicked

    private void l54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l54MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l54MouseClicked

    private void l55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l55MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l55MouseClicked

    private void l56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l56MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l56MouseClicked

    private void l57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l57MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l57MouseClicked

    private void l58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l58MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l58MouseClicked

    private void l59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l59MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l59MouseClicked

    private void l60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l60MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l60MouseClicked

    private void l61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l61MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l61MouseClicked

    private void l62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l62MouseClicked

    private void l63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l63MouseClicked

    private void l64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l64MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l64MouseClicked

    private void acertou3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acertou3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acertou3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatalhaClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatalhaClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatalhaClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatalhaClienteTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BatalhaClienteTela().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton acertou;
    public javax.swing.JButton acertou1;
    public javax.swing.JButton acertou3;
    public javax.swing.JPanel envio;
    private javax.swing.JPanel envio1;
    private javax.swing.JPanel envio2;
    private javax.swing.JPanel envio3;
    public javax.swing.JButton errou;
    public javax.swing.JButton errou1;
    public javax.swing.JButton errou3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton l1;
    public javax.swing.JButton l10;
    public javax.swing.JButton l11;
    public javax.swing.JButton l12;
    public javax.swing.JButton l13;
    public javax.swing.JButton l14;
    public javax.swing.JButton l15;
    public javax.swing.JButton l16;
    public javax.swing.JButton l17;
    public javax.swing.JButton l18;
    public javax.swing.JButton l19;
    public javax.swing.JButton l2;
    public javax.swing.JButton l20;
    public javax.swing.JButton l21;
    public javax.swing.JButton l22;
    public javax.swing.JButton l23;
    public javax.swing.JButton l24;
    public javax.swing.JButton l25;
    public javax.swing.JButton l26;
    public javax.swing.JButton l27;
    public javax.swing.JButton l28;
    public javax.swing.JButton l29;
    public javax.swing.JButton l3;
    public javax.swing.JButton l30;
    public javax.swing.JButton l31;
    public javax.swing.JButton l32;
    public javax.swing.JButton l33;
    public javax.swing.JButton l34;
    public javax.swing.JButton l35;
    public javax.swing.JButton l36;
    public javax.swing.JButton l37;
    public javax.swing.JButton l38;
    public javax.swing.JButton l39;
    public javax.swing.JButton l4;
    public javax.swing.JButton l40;
    public javax.swing.JButton l41;
    public javax.swing.JButton l42;
    public javax.swing.JButton l43;
    public javax.swing.JButton l44;
    public javax.swing.JButton l45;
    public javax.swing.JButton l46;
    public javax.swing.JButton l47;
    public javax.swing.JButton l48;
    public javax.swing.JButton l49;
    public javax.swing.JButton l5;
    public javax.swing.JButton l50;
    public javax.swing.JButton l51;
    public javax.swing.JButton l52;
    public javax.swing.JButton l53;
    public javax.swing.JButton l54;
    public javax.swing.JButton l55;
    public javax.swing.JButton l56;
    public javax.swing.JButton l57;
    public javax.swing.JButton l58;
    public javax.swing.JButton l59;
    public javax.swing.JButton l6;
    public javax.swing.JButton l60;
    public javax.swing.JButton l61;
    public javax.swing.JButton l62;
    public javax.swing.JButton l63;
    public javax.swing.JButton l64;
    public javax.swing.JButton l7;
    public javax.swing.JButton l8;
    public javax.swing.JButton l9;
    private javax.swing.JButton suaVez;
    public javax.swing.JButton vidaRestante;
    // End of variables declaration//GEN-END:variables

 


        
    

/*public class ReceberListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           escritor.println(t1.setBackground(Color.red));
           escritor.flush();           
           
        }*/
        
    
    
    void configurarRede(BatalhaClienteTela b) throws IOException{
        
        try {
              //Socket socket = new Socket("192.168.1.112", 5000);
            out = new DataOutputStream(socket.getOutputStream());
            in = new DataInputStream(socket.getInputStream());
             new Thread(new EscutaServidor(b)).start();
          
            //Socket socket = new Socket("127.0.0.1", 5000);
        /* escritor = new PrintWriter(socket.getOutputStream());
         receptor =  new DataInputStream(socket.getInputStream());*/
        
        
        } catch (Exception e) {
            e.printStackTrace();
        }
      
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setarIconesDefault() {
        
        acertou.setIcon(iconAcertou);
        errou.setIcon(iconErrou);
        l1.setIcon(defaultIcon);
        l2.setIcon(defaultIcon);
        l3.setIcon(defaultIcon);
        l4.setIcon(defaultIcon);
        l5.setIcon(defaultIcon);
        l6.setIcon(defaultIcon);
        l7.setIcon(defaultIcon);;
        l8.setIcon(defaultIcon);
        l9.setIcon(defaultIcon);
        l10.setIcon(defaultIcon);
        l11.setIcon(defaultIcon);
        l12.setIcon(defaultIcon);
        l13.setIcon(defaultIcon);
        l14.setIcon(defaultIcon);
        l15.setIcon(defaultIcon);
        l16.setIcon(defaultIcon);
        
        l33.setIcon(defaultIcon);
        l34.setIcon(defaultIcon);
        l35.setIcon(defaultIcon);
	l48.setIcon(defaultIcon);
        l36.setIcon(defaultIcon);
        l37.setIcon(defaultIcon);
        l38.setIcon(defaultIcon);
        l39.setIcon(defaultIcon);;
        l40.setIcon(defaultIcon);
        l41.setIcon(defaultIcon);
        l42.setIcon(defaultIcon);
        l43.setIcon(defaultIcon);
        l44.setIcon(defaultIcon);
        l45.setIcon(defaultIcon);
        l46.setIcon(defaultIcon);
        l47.setIcon(defaultIcon);
    }

   
    
    private class EscutaServidor implements Runnable,ActionListener {
         BatalhaClienteTela aThis;
        
        
       
       

        public EscutaServidor(BatalhaClienteTela aThis) {
            this.aThis = aThis;
        }
        
        
         private EscutaServidor() {
           
        }

        /*
         * Sobrescreve metodo run
         */
        @Override
        public void run() {

            String ss;
            String s;
            String e="";
            String tiro = "";    
            try {
                while (true) {
                    s = in.readUTF();
                    if(aThis.getPlayer().getVida() < 1){
                        break;
                    }
                    System.out.println(s+"\n"); 
                    /*String idPlayerEnviouMsg =s.substring(0,1);*/
                    String idPlayerRecebeuMsg =s.substring(0,1);
                    
                    String msg =s.substring(0,1);
                  
                    if(!s.equals("start") ){
                        //se for um tiro recebido retorna false
                       if( this.verificaSeEhTiroDadoOuRetornoDeAcertoErro(msg) == false){
                               
                            String localizacaoTiro =s.substring(1); 
                            aThis.desbloqueiaJogada();
                            aThis.vidaRestante.setText(Integer.toString( aThis.getPlayer().getVida()));                            
                            String acertoErro = this.verivicarAcertoOuErro(aThis,localizacaoTiro);
                             //enviaRetorno
                             this.enviaRetornoAcertoErro( localizacaoTiro,acertoErro );
                             this.setaOMeuTabuleiroComOTiroRecebido(localizacaoTiro,acertoErro);
                            /* if(acertoErro.equals("c")){
                                aThis.getPlayer().diminuiVida(); 
                                aThis.getPlayer().getTabuleiroPlayer().getPontosTabuleiro().get(Integer.parseInt(localizacaoTiro)).setTemNavio(false);
                                aThis.getPlayer().getTabuleiroPlayer().getPontosTabuleiro().get(Integer.parseInt(localizacaoTiro)).setPermiteJogada(false);
                             }*/
                             aThis.desbloqueiaJogada();
                            
                        }else {//se for um retorno de acerto ou erro 
                              String retorno =s.substring(0,1);
                              String localizacaoTiro =s.substring(1);                                 
                             this.setaOTabuleiroDoOponenteComOtiroDado(localizacaoTiro,retorno);
                             
                             aThis.bloqueiaJogada();
                        }
                    
                    }
                    
                 
                }
               // JOptionPane.showMessageDialog(aThis, "Perdeu");
              
            } catch (Exception ex) {
            }
          int sai= JOptionPane.showConfirmDialog(aThis, "Perdeu");
          if(sai == 0)
            System.exit(0);
        }
        
        private String verivicarAcertoOuErro(BatalhaClienteTela p,String index) {
           
            for (PontoTabuleiro ponto :p.getPlayer().getTabuleiroPlayer().pontosTabuleiro) {
                if(ponto.getEndereco() == Integer.parseInt(index)){
                    if(ponto.getTemNavio()){
                        ponto.setTemNavio(false);
                        aThis.getPlayer().diminuiVida();
                        return "c";
                    }   
                }   
            }
            return "e";
        }
        
        /* private String setarPoicaoAvvaiparaAcertada(BatalhaClienteTela p,String index) {
           
            for (PontoTabuleiro ponto :p.getPlayer().getTabuleiroPlayer().pontosTabuleiro) {
                if(ponto.getEndereco() == Integer.parseInt(index)){
                    if(ponto.getTemNavio()){
                        ponto.setTemNavio(false);
                        return "c";
                    }   
                }   
            }
            return "e";
        }*/
        
        private void setaOMeuTabuleiroComOTiroRecebido(String s,String v) {
              // String caminhoImagens ="C:/Users/rodrigolucke/Documents/NetBeansProjects/BatalhaNavalLuckeDani/src";
           //  Icon iconAcertou = new ImageIcon(aThis.caminhoImagens+"/images/acertou.gif");
           //  Icon iconErrou = new ImageIcon(aThis.caminhoImagens+"/images/errou.gif");
            aThis.getPlayer().getTabuleiroPlayer().getPontosTabuleiro().get(Integer.parseInt(s)).setTemNavio(false);
          
            if(s.equals("0")){
                if(v.equals("c")){ 
                  l33.setIcon(iconAcertou);
                }else{
                  l33.setIcon(iconErrou);
                }
            }
            if(s.equals("1")){
                if(v.equals("c")){
                    l34.setIcon(iconAcertou);
                }else{
                    l34.setIcon(iconErrou);
                }
            }
            if(s.equals("2")){
                if(v.equals("c")){
                    l35.setIcon(iconAcertou);
                }else{
                    l35.setIcon(iconErrou);
                }
            }
            if(s.equals("3")){
                if(v.equals("c")){
                    l48.setIcon(iconAcertou);
                }else{
                    l48.setIcon(iconErrou);
                }
            }
            if(s.equals("4")){
                if(v.equals("c")){                         
                    l36.setIcon(iconAcertou);
                }else{
                    l36.setIcon(iconErrou);
                }
            }
            if(s.equals("5")){
                if(v.equals("c")){
                    l37.setIcon(iconAcertou);
                }else{
                    l37.setIcon(iconErrou);
                }
            }
            if(s.equals("6")){
                if(v.equals("c")){
                    l38.setIcon(iconAcertou);;
                }else{
                    l38.setIcon(iconErrou);
                }
            }
            if(s.equals("7")){
                if(v.equals("c")){
                    l39.setIcon(iconAcertou);
                }else{
                    l39.setIcon(iconErrou);
                }
            }if(s.equals("8")){
                if(v.equals("c")){                         
                    l40.setIcon(iconAcertou);
                }else{
                    l40.setIcon(iconErrou);
                }
            }if(s.equals("9")){
                if(v.equals("c")){                         
                    l41.setIcon(iconAcertou);
                }else{
                    l41.setIcon(iconErrou);
                }
            }if(s.equals("10")){
                if(v.equals("c")){                         
                    l42.setIcon(iconAcertou);
                }else{
                    l42.setIcon(iconErrou);
                }
            }
            if(s.equals("11")){
                if(v.equals("c")){                         
                    l43.setIcon(iconAcertou);
                }else{
                    l43.setIcon(iconErrou);
                }
            }
            if(s.equals("12")){
                if(v.equals("c")){                         
                    l44.setIcon(iconAcertou);
                }else{
                    l44.setIcon(iconErrou);
                }
            }
            if(s.equals("13")){
                if(v.equals("c")){                         
                    l45.setIcon(iconAcertou);
                }else{
                    l45.setIcon(iconErrou);
                }
            }
            if(s.equals("14")){
                if(v.equals("c")){                         
                    l46.setIcon(iconAcertou);
                }else{
                    l46.setIcon(iconErrou);
                }
            }                          

            if(s.equals("15")){
                if(v.equals("c")){                         
                    l47.setIcon(iconAcertou);
                }else{
                    l47.setIcon(iconErrou);
                }
            }
        }    
        
        
        

        private boolean verivicarSePossuiNavio(BatalhaClienteTela p,String index) {
           
            for (PontoTabuleiro ponto :p.getPlayer().getTabuleiroPlayer().pontosTabuleiro) {
                if(ponto.getEndereco() == Integer.parseInt(index)){
                    if(ponto.getTemNavio()){
                        ponto.setTemNavio(false);
                        return true;
                    }   
                }   
            }
            return false;
        }

       
        
     private void setaOTabuleiroDoOponenteComOtiroDado(String s,String v) {
              // String caminhoImagens ="C:/Users/rodrigolucke/Documents/NetBeansProjects/BatalhaNavalLuckeDani/src";
           /*  Icon iconAcertou = new ImageIcon(aThis.caminhoImagens+"/images/acertou.gif");
             Icon iconErrou = new ImageIcon(aThis.caminhoImagens+"/images/errou.gif");*/
            // aThis.getPlayer().getTabuleiroPlayer().getPontosTabuleiro().get(Integer.parseInt(s)).setTemNavio(false);
              // String caminhoImagens ="C:/Users/rodrigolucke/Documents/NetBeansProjects/BatalhaNavalLuckeDani/src";
           
          
             
          
           if(v.equals("c")){
                aThis.player.diminuiVida();
            }
            if(s.equals("0")){
                if(v.equals("c")){ 
                   l1.setIcon(iconAcertou);
                }else{
                   l1.setIcon(iconErrou);
                }
            }
            if(s.equals("1")){
                if(v.equals("c")){
                    l2.setIcon(iconAcertou);
                }else{
                    l2.setIcon(iconErrou);
                }
            }
            if(s.equals("2")){
                if(v.equals("c")){
                    l3.setIcon(iconAcertou);
                }else{
                    l3.setIcon(iconErrou);
                }
            }
            if(s.equals("3")){
                if(v.equals("c")){
                    l4.setIcon(iconAcertou);
                }else{
                    l4.setIcon(iconErrou);
                }
            }
            if(s.equals("4")){
                if(v.equals("c")){                         
                    l5.setIcon(iconAcertou);
                }else{
                    l5.setIcon(iconErrou);
                }
            }
            if(s.equals("5")){
                if(v.equals("c")){
                    l6.setIcon(iconAcertou);
                }else{
                    l6.setIcon(iconErrou);
                }
            }
            if(s.equals("6")){
                if(v.equals("c")){
                    l7.setIcon(iconAcertou);;
                }else{
                    l7.setIcon(iconErrou);
                }
            }
            if(s.equals("7")){
                if(v.equals("c")){
                    l8.setIcon(iconAcertou);
                }else{
                    l8.setIcon(iconErrou);
                }
            }if(s.equals("8")){
                if(v.equals("c")){                         
                    l9.setIcon(iconAcertou);
                }else{
                    l9.setIcon(iconErrou);
                }
            }if(s.equals("9")){
                if(v.equals("c")){                         
                    l10.setIcon(iconAcertou);
                }else{
                    l10.setIcon(iconErrou);
                }
            }if(s.equals("10")){
                if(v.equals("c")){                         
                    l11.setIcon(iconAcertou);
                }else{
                    l11.setIcon(iconErrou);
                }
            }
            if(s.equals("11")){
                if(v.equals("c")){                         
                    l12.setIcon(iconAcertou);
                }else{
                    l12.setIcon(iconErrou);
                }
            }
            if(s.equals("12")){
                if(v.equals("c")){                         
                    l13.setIcon(iconAcertou);
                }else{
                    l13.setIcon(iconErrou);
                }
            }
            if(s.equals("13")){
                if(v.equals("c")){                         
                    l14.setIcon(iconAcertou);
                }else{
                    l14.setIcon(iconErrou);
                }
            }
            if(s.equals("14")){
                if(v.equals("c")){                         
                    l15.setIcon(iconAcertou);
                }else{
                    l15.setIcon(iconErrou);
                }
            }                          

            if(s.equals("15")){
                if(v.equals("c")){                         
                    l16.setIcon(iconAcertou);
                }else{
                    l16.setIcon(iconErrou);
                }
            }
           
            
        }                

        private void enviaRetornoAcertoErro(String ss) {
            try {  
                out = new DataOutputStream(socket.getOutputStream());
            } catch (IOException ex) {
                Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                out.writeUTF(ss);
            } catch (IOException ex) {
                Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                out.flush();
            } catch (IOException ex) {
                Logger.getLogger(BatalhaClienteTela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        private boolean verificaSeEhTiroDadoOuRetornoDeAcertoErro(String msg ) {
             if(!((msg.equals("e")) || (msg.equals("c")))){
                return false;
             }else{
                return true;
             }
        }

        private void enviaRetornoAcertoErro(String localizacaoTiro, String acertoErro) throws IOException {
            out = new DataOutputStream(socket.getOutputStream());
            out.writeUTF(acertoErro+""+localizacaoTiro);
            out.flush();
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        
    }
    private void bloqueiaJogada() {
           
            //envio.setVisible(false);
            envio.setEnabled(false);       
            vidaRestante.setVisible(true);
            this.vidaRestante.setText(Integer.toString( this.getPlayer().getVida()));
            this.suaVez.setVisible(false);
            this.suaVez.setBackground(Color.red);
            
            Component[] componentes = envio.getComponents(); // altere para o nome da variavel do seu painel
                    for (Component componente : componentes) {
                        componente.setEnabled(false);
                    }

                     
        }

        void desbloqueiaJogada() {
            
            //envio.setVisible(true);
            envio.setEnabled(true);
            //JOptionPane.showMessageDialog(this, "Sua vez de jogar!");
            this.suaVez.setVisible(true);
            this.suaVez.setBackground(Color.cyan);
           // vidaRestante.setVisible(false);
           this.vidaRestante.setText(Integer.toString( this.getPlayer().getVida()));
           
            Component[] componentes = envio.getComponents(); // altere para o nome da variavel do seu painel
                    for (Component componente : componentes) {
                        componente.setEnabled(true);
                    }
        }
       
}
