/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulaMenu;

import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;

/**
 *
 * @author m72583
 */
public class TelaPrincipal extends javax.swing.JFrame {
    TelaInserir ti;
    TelaExcluir te;
    TelaConsultar tc;
  
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setSize(600, 600);
        
        ti = new TelaInserir(); 
        this.ti.setVisible(false);        
        this.getContentPane().add(ti);
       
        
        te = new TelaExcluir();
        this.te.setVisible(false);
        this.getContentPane().add(te);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        tarefas = new javax.swing.JMenu();
        inserir = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        consultar = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        grafico = new javax.swing.JMenu();
        sobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tarefas.setText("Tarefas");
        tarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarefasMouseClicked(evt);
            }
        });

        inserir.setText("Inserir");
        inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserirMouseClicked(evt);
            }
        });
        tarefas.add(inserir);

        excluir.setText("Excluir");
        excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMouseClicked(evt);
            }
        });
        tarefas.add(excluir);

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });
        tarefas.add(consultar);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        tarefas.add(sair);

        jMenuBar1.add(tarefas);

        grafico.setText("Gráfico");
        jMenuBar1.add(grafico);

        sobre.setText("Sobre");
        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarefasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tarefasMouseClicked

    private void inserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserirMouseClicked
        System.out.println("aulaMenu.TelaPrincipal.inserirMouseClicked()");
         if(ti.isVisible())
           ti.setVisible(false);
         else
          ti.setVisible(true);         
          ti.setLocation(200, -100);
    }//GEN-LAST:event_inserirMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMouseClicked
        if(te.isVisible())
           te.setVisible(false);
        else
          te.setVisible(true);         
          te.setLocation(200, -100);
    }//GEN-LAST:event_excluirMouseClicked

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        
        if(tc.isVisible()){
           tc.setVisible(false);
        }else{
          tc.setVisible(true);  
        }
          tc.setLocation(200, -100);
    }//GEN-LAST:event_consultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultar;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JMenu grafico;
    private javax.swing.JMenuItem inserir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenu sobre;
    private javax.swing.JMenu tarefas;
    // End of variables declaration//GEN-END:variables
}
