/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecladoTracer;

/**
 *
 * @author m78172
 */
public class Teclado extends javax.swing.JFrame {

    /**
     * Creates new form Teclado
     */
    public Teclado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 10, 70, 30);
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 10, 70, 30);
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 10, 70, 30);
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 10, 70, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 230, 300, 40);

        jButton5.setText("Z");
        getContentPane().add(jButton5);
        jButton5.setBounds(100, 130, 40, 23);

        jButton6.setText("Q");
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 70, 40, 23);

        jButton7.setText("W");
        getContentPane().add(jButton7);
        jButton7.setBounds(80, 70, 50, 23);

        jButton8.setText("E");
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 70, 40, 23);

        jButton9.setText("R");
        getContentPane().add(jButton9);
        jButton9.setBounds(170, 70, 40, 23);

        jButton10.setText("T");
        getContentPane().add(jButton10);
        jButton10.setBounds(210, 70, 40, 23);

        jButton11.setText("Y");
        getContentPane().add(jButton11);
        jButton11.setBounds(250, 70, 40, 23);

        jButton12.setText("U");
        getContentPane().add(jButton12);
        jButton12.setBounds(290, 70, 40, 23);

        jButton13.setText("I");
        getContentPane().add(jButton13);
        jButton13.setBounds(330, 70, 40, 23);

        jButton14.setText("O");
        getContentPane().add(jButton14);
        jButton14.setBounds(370, 70, 40, 23);

        jButton15.setText("P");
        getContentPane().add(jButton15);
        jButton15.setBounds(410, 70, 40, 23);

        jButton16.setText("D");
        getContentPane().add(jButton16);
        jButton16.setBounds(140, 100, 40, 23);

        jButton17.setText("A");
        getContentPane().add(jButton17);
        jButton17.setBounds(60, 100, 40, 23);

        jButton18.setText("G");
        getContentPane().add(jButton18);
        jButton18.setBounds(220, 100, 40, 23);

        jButton19.setText("H");
        getContentPane().add(jButton19);
        jButton19.setBounds(260, 100, 40, 23);

        jButton20.setText("S");
        getContentPane().add(jButton20);
        jButton20.setBounds(100, 100, 40, 23);

        jButton21.setText("K");
        getContentPane().add(jButton21);
        jButton21.setBounds(340, 100, 40, 23);

        jButton22.setText("L");
        getContentPane().add(jButton22);
        jButton22.setBounds(380, 100, 40, 23);

        jButton23.setText("F");
        getContentPane().add(jButton23);
        jButton23.setBounds(180, 100, 40, 23);

        jButton24.setText("X");
        getContentPane().add(jButton24);
        jButton24.setBounds(140, 130, 40, 23);

        jButton25.setText("M");
        getContentPane().add(jButton25);
        jButton25.setBounds(340, 130, 40, 23);

        jButton26.setText("J");
        getContentPane().add(jButton26);
        jButton26.setBounds(300, 100, 40, 23);

        jButton27.setText("B");
        getContentPane().add(jButton27);
        jButton27.setBounds(260, 130, 40, 23);

        jButton28.setText("N");
        getContentPane().add(jButton28);
        jButton28.setBounds(300, 130, 40, 23);

        jButton29.setText("C");
        getContentPane().add(jButton29);
        jButton29.setBounds(180, 130, 40, 23);

        jButton30.setText("V");
        getContentPane().add(jButton30);
        jButton30.setBounds(220, 130, 40, 23);
        getContentPane().add(jButton31);
        jButton31.setBounds(140, 170, 170, 30);

        setBounds(0, 0, 500, 380);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
